"""Target broker boundary; legacy KIS adapter is not yet a conforming adapter."""
from typing import Protocol, Mapping, Any
from src.core.models.contracts import OrderIntent


class Broker(Protocol):
    def account_snapshot(self) -> Mapping[str, Any]: ...
    def submit(self, intent: OrderIntent) -> str: ...
    def order_snapshot(self, order_id: str) -> Mapping[str, Any]: ...
    def cancel(self, order_id: str) -> Mapping[str, Any]: ...
